var files =
[
    [ "/home/darkomen/Desktop/Proyecto/actuador.cpp", "actuador_8cpp.html", null ],
    [ "/home/darkomen/Desktop/Proyecto/actuador.h", "actuador_8h.html", null ],
    [ "/home/darkomen/Desktop/Proyecto/actuadoranalogico.cpp", "actuadoranalogico_8cpp.html", null ],
    [ "/home/darkomen/Desktop/Proyecto/actuadoranalogico.h", "actuadoranalogico_8h.html", null ],
    [ "/home/darkomen/Desktop/Proyecto/actuadordiscreto.cpp", "actuadordiscreto_8cpp.html", null ],
    [ "/home/darkomen/Desktop/Proyecto/actuadordiscreto.h", "actuadordiscreto_8h.html", null ],
    [ "/home/darkomen/Desktop/Proyecto/comunicaciones.cpp", "comunicaciones_8cpp.html", null ],
    [ "/home/darkomen/Desktop/Proyecto/comunicaciones.h", "comunicaciones_8h.html", null ],
    [ "/home/darkomen/Desktop/Proyecto/ficheros.cpp", "ficheros_8cpp.html", null ],
    [ "/home/darkomen/Desktop/Proyecto/ficheros.h", "ficheros_8h.html", null ],
    [ "/home/darkomen/Desktop/Proyecto/funciones.cpp", "funciones_8cpp.html", "funciones_8cpp" ],
    [ "/home/darkomen/Desktop/Proyecto/funciones.h", "funciones_8h.html", "funciones_8h" ],
    [ "/home/darkomen/Desktop/Proyecto/main.cpp", "main_8cpp.html", "main_8cpp" ],
    [ "/home/darkomen/Desktop/Proyecto/nodo.cpp", "nodo_8cpp.html", null ],
    [ "/home/darkomen/Desktop/Proyecto/nodo.h", "nodo_8h.html", null ],
    [ "/home/darkomen/Desktop/Proyecto/nodocentral.cpp", "nodocentral_8cpp.html", null ],
    [ "/home/darkomen/Desktop/Proyecto/nodocentral.h", "nodocentral_8h.html", null ],
    [ "/home/darkomen/Desktop/Proyecto/regulador.cpp", "regulador_8cpp.html", null ],
    [ "/home/darkomen/Desktop/Proyecto/regulador.h", "regulador_8h.html", null ],
    [ "/home/darkomen/Desktop/Proyecto/sensor.cpp", "sensor_8cpp.html", null ],
    [ "/home/darkomen/Desktop/Proyecto/sensor.h", "sensor_8h.html", null ],
    [ "/home/darkomen/Desktop/Proyecto/sensoranalogico.cpp", "sensoranalogico_8cpp.html", null ],
    [ "/home/darkomen/Desktop/Proyecto/sensoranalogico.h", "sensoranalogico_8h.html", null ],
    [ "/home/darkomen/Desktop/Proyecto/sensordiscreto.cpp", "sensordiscreto_8cpp.html", null ],
    [ "/home/darkomen/Desktop/Proyecto/sensordiscreto.h", "sensordiscreto_8h.html", null ],
    [ "/home/darkomen/Desktop/Proyecto/simulador.cpp", "simulador_8cpp.html", null ],
    [ "/home/darkomen/Desktop/Proyecto/simulador.h", "simulador_8h.html", null ]
];